profile-name: dev

spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/BAEKJOON_STATUS?rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
#        format_sql: :true
#        show_sql: true
#        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          batch_size: 100

server:
  port: 9090
