profile-name: prod

database:
  date-format: DATE_FORMAT({0}, {1})
  year-format: %Y

spring:
  main:
    web-application-type: none
  batch:
    jdbc:
      initialize-schema: never
    job:
      names: ${job.name:NONE}
  config:
    import: application-aws.yaml
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    database: mysql
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    root: info
