profile-name: prod

database:
  date-format: DATE_FORMAT({0}, {1})
  year-format: %Y

spring:
  config:
    import: application-aws.yaml
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    database: mysql
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
logging:
  level:
    root: info
