profile-name: dev
token:
  secret: test

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/BAEKJOON_STATUS?rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
#        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 100
    open-in-view: false
server:
  port: 8080
logging:
  level:
    org.hibernate.SQL: debug
